Repository ITMO-TECH-TEAM-3/TEAM-3-3, pull requests merged in 2022-06, with the labels that each got.

#44 feat: add matches service logic (#25)
  src/main/java/com/tech/tournaments/service/impl/MatchServiceImpl.java
Labels: feature

#47 feat(): unit test for matches creation
  src/main/java/com/tech/tournaments/model/Match.java
  src/main/java/com/tech/tournaments/repository/MatchRepository.java
  src/main/java/com/tech/tournaments/service/BracketService.java
  src/main/java/com/tech/tournaments/service/MatchService.java
  src/main/java/com/tech/tournaments/service/impl/BracketServiceImpl.java
  src/main/java/com/tech/tournaments/service/impl/MatchServiceImpl.java
  src/test/java/com/tech/tournaments/service/MatchServiceTests.java
Labels: feature, minor

#51 fix(): bugs
  src/main/java/com/tech/tournaments/controller/MatchController.java
  src/main/java/com/tech/tournaments/model/Bracket.java
  src/main/java/com/tech/tournaments/model/Match.java
  src/main/java/com/tech/tournaments/model/MatchResult.java
  src/main/java/com/tech/tournaments/model/TeamRelationship.java
  src/main/java/com/tech/tournaments/model/Tournament.java
  src/main/java/com/tech/tournaments/model/TournamentResult.java
  src/main/java/com/tech/tournaments/repository/MatchRepository.java
  src/main/java/com/tech/tournaments/repository/TournamentRepository.java
  src/main/java/com/tech/tournaments/service/MatchService.java
  src/main/java/com/tech/tournaments/service/TournamentService.java
  src/main/java/com/tech/tournaments/service/impl/BracketServiceImpl.java
  src/main/java/com/tech/tournaments/service/impl/MatchServiceImpl.java
  src/main/java/com/tech/tournaments/service/impl/TournamentServiceImpl.java
Labels: fix

#52 fix(): bug fixes
  src/main/java/com/tech/tournaments/controller/MatchController.java
  src/main/java/com/tech/tournaments/model/Bracket.java
  src/main/java/com/tech/tournaments/model/Match.java
  src/main/java/com/tech/tournaments/model/MatchResult.java
  src/main/java/com/tech/tournaments/model/TeamRelationship.java
  src/main/java/com/tech/tournaments/model/Tournament.java
  src/main/java/com/tech/tournaments/model/TournamentResult.java
  src/main/java/com/tech/tournaments/repository/MatchRepository.java
  src/main/java/com/tech/tournaments/repository/TournamentRepository.java
  src/main/java/com/tech/tournaments/service/MatchService.java
  src/main/java/com/tech/tournaments/service/TournamentService.java
  src/main/java/com/tech/tournaments/service/impl/BracketServiceImpl.java
  src/main/java/com/tech/tournaments/service/impl/MatchServiceImpl.java
  src/main/java/com/tech/tournaments/service/impl/TournamentServiceImpl.java
Labels: fix, major
